server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: 127.0.0.1
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serverUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
